### ISSUE TITLE
ODRC: Create Helm charts

### ISSUE THREAD

**Issue by sergei-maertens** [GPP-Woo/GPP-publicatiebank#107]
The application needs to be deployed using Helm, so we require the relevant charts.

**Tasks**

* [x] Create Helm chart for registration component (this repository). It's a standard Maykin Django project, with:
     - OIDC login for admin
     - No celery (no worker, flower, beat)
     - Redis is used for cache
     - PostgreSQL database
     - Available environment variables are [documented](https://odrc.readthedocs.io/en/latest/installation/config.html). Some are unused: `SITE_ID`, `CSRF_TRUSTED_ORIGINS`, `NOTIFICATIONS_DISABLED`, `DISABLE_2FA` (not sure about this, either way, it should not be disabled): https://github.com/maykinmedia/charts/pull/141
* [x] Create chart for OPDC: https://github.com/maykinmedia/charts/pull/143
* [ ] Create an Umbrella chart - the registration component needs an Open Zaak instance (or other Documents API implementation). It should be configurable to use an existing instance, or deploy a fresh, isolated Open Zaak instance.
