### ISSUE TITLE
ODRC: muteren, publiceren of intrekken publicatie

### ISSUE THREAD

**Issue by RutgerICATT** [GPP-Woo/GPP-publicatiebank#6]
Als beheerder wil ik een publicatie kunnen wijzigen of intrekken, zodat ik andermans fouten kan herstellen.

**Acceptatie criteria**
- [x] Als bekeerder wil ik wanneer ik een publicatie inzie (#50) de gegevens kunnen wijzigen.
  - M.u.v.  UUID en creatiedatum uiteraard
- [x] Als beheerder wil ik ook de gegevens op een document kunnen wijzigen.
- [x]Als beheerder wil ik documenten incl. metadata kunnen toevoegen. (aparte user story toevoegen voor bestand uploaden)
- [x] Als beheerder wil ik een publicatie kunnen intrekken.
  - Optioneel: Er wordt gevraagd: "Weet u het zeker?"
  - Zowel de publicatie als de daaraan gekoppelde documenten krijgen de `publicatiestatus` "ingetrokken"
 - [x] Als beheerder wil ik een document kunnen intrekken.
   - Het documenten krijgt de `publicatiestatus` "ingetrokken".
- [x] Een ingetrokken publicatie kan niet meer opnieuw gepubliceerd worden.
- [x] Een ingetrokken publicatie kan niet gewijzigd worden. De documenten evenmin.
 - [x] Een ingetrokken document (van een gepubliceerde publicatie) kan wel gewijzigd en/of opnieuw gepubliceerd worden.
 - [x] Mutaties, etc worden gelogd.
 - [x] Documentatie is bijgewerkt.

**Taken**

- [ ]

**Comment by sergei-maertens** [comment]
Should be provided via #3
